version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '18:00'
      timezone: Asia/Singapore
    groups:
       dependencies:
          patterns: ['*']

  - package-ecosystem: docker
    directory: /
    ignore:
      - dependency-name: python
        update-types: ["version-update:semver-minor"]
      - dependency-name: nvidia/cuda
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
      time: '18:00'
      timezone: Asia/Singapore
    groups:
       dependencies:
          patterns: ['*']

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: '18:00'
      timezone: Asia/Singapore
    groups:
       dependencies:
          patterns: ['*']
