name: Clippy

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - .github/workflows/clippy.yml
      - client/**
      - language/**

jobs:
  clippy:
    uses: winstxnhdw/actions/.github/workflows/clippy.yml@main
    with:
      working-directory: ${{ matrix.working-directory }}
    strategy:
      matrix:
        working-directory: [client, language]
